AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
 S3 file uploads
 AWS Serverless Application upload files 
Parameters:
  BucketName:
    Type: String
    AllowedPattern: (?=^.{3,63}$)(?!^(\d+\.)+\d+$)(^(([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])\.)*([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])$)
    Description: Enter a S3 bucket name
  StageName:
    Type: String
    Default: 'prod'
    Description: Enter the API Stage name
Globals:
  Function:
    Timeout: 3
Resources:
  UploadURL:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: app.uploadHandler
      Runtime: nodejs12.x
      Events:
        UploadAgc:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref FileUploadApi
            Path: /upload/url
            Method: get
            RequestParameters:
             - method.request.querystring.file_name
             - method.request.querystring.bucket_name
      Policies:
        #Give access to S3 Bucket
        - S3CrudPolicy:
            BucketName: 
              !Ref FileUploadBucket
  FileUploadApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn:
      - FileUploadApiStage
    Properties:
      Name: FileUploadApiKey
      Description: API key to use for the S3 bucket uploader
      Enabled: true
      StageKeys:
        - RestApiId: !Ref FileUploadApi
          StageName: !Ref StageName
  FileUploadApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: FileUploadApi
      StageName: !Ref StageName
      Auth:
        ApiKeyRequired: true
  FileUploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 
        !Ref BucketName

Outputs:
  UploadApiInfo:
    Description: "API Gateway endpoint URL for Prod stage for Upload function:"
    Value: !Sub "https://${FileUploadApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/upload/url"
  FileUploadApiKeyInfo:
    Description: "API Key:"
    Value: !Ref FileUploadApiKey
  UploadFunctionInfo:
    Description: ""
    Value: !GetAtt UploadURL.Arn
  UploadFunctionIamRoleInfo:
    Description: "Implicit IAM Role created for UploadURL function:"
    Value: !GetAtt UploadURL.Arn
  UploadFileBucketInfo:
    Description: "S3 Bucket:"
    Value: !GetAtt FileUploadBucket.Arn
